config/routes.rb
Rails.application.routes.draw do

  resources :servers

  resources :users

  root 'servers#index'

  get '/signup',  to: 'users#new'

  resources :lists do
    resources :items do
      collection do
        get :edit_multiple
        put :update_multiple
      end
    end
  end
  

end

app/models/categorization.rb
class Categorization < ActiveRecord::Base
	belongs_to :item
	belongs_to :category
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :categorizations
	has_many :items, :through => :categorizations
end

app/models/item.rb
class Item < ActiveRecord::Base
	belongs_to :list
	has_many :categorizations
	has_many :categories, :through => :categorizations
end

app/models/list.rb
class List < ActiveRecord::Base
	has_many :items, dependent: :destroy
end

app/models/server.rb
class Server < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
	before_save { self.email = email.downcase }
	validates :name, presence: true, length: { maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
	has_secure_password
  validates :password, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

	before_action :get_list

  def get_list
  	@list = List.find(params[:list_id])
  end

  def index
    @items = @list.items.all
  end

  def show
  	@item = @list.items.find(params[:id])
  end

  def new
  	@item = @list.items.new
  end

  def edit
    @item = @list.items.find(params[:id])
  end


  def create
  	@item = @list.items.new(item_params)
  	if @item.save
  		redirect_to [@list, @item]
  	else
  		render action: "new"
  	end
  end

  def update
    @item = @list.items.find(params[:id])
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @list, notice: 'Item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to @list, notice: "Item was successfully destroyed."
  end

  def edit_multiple
    @items = Item.where(id: params[:item_ids])
  end

  def update_multiple
    Item.update(params[:items].keys, params[:items].values)
    redirect_to @list
  end

  def purchased
    Item.where(id: params[:item_ids]).update_all(purchased: true)
    redirect_to @list
  end

  private

  def item_params
  	params.require(:item).permit(:name, :brand, :location, :price, :quantity, :purchased)
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
  	@lists = List.all
  	respond_to do |format|
  		format.html
  		format.json {render json: @lists}
  	end
  end

  def show
  	@list = List.find(params[:id])
  	@items = @list.items
  	respond_to do |format|
  		format.html
  		format.json {render json: @items}
  	end
  end

  def new
  	@list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to @list
    else
      render action: "new"
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to root_path, notice: "List was succesfully destroyed."
  end


  private

  def list_params
  	params.require(:list).permit(:name, :location)
  end
end

app/controllers/servers_controller.rb
class ServersController < ApplicationController
  before_action :set_server, only: [:show, :edit, :update, :destroy]

  # GET /servers
  # GET /servers.json
  def index
    @servers = Server.all
  end

  # GET /servers/1
  # GET /servers/1.json
  def show
  end

  # GET /servers/new
  def new
    @server = Server.new
  end

  # GET /servers/1/edit
  def edit
  end

  # POST /servers
  # POST /servers.json
  def create
    @server = Server.new(server_params)

    respond_to do |format|
      if @server.save
        format.html { redirect_to @server, notice: 'Server was successfully created.' }
        format.json { render :show, status: :created, location: @server }
      else
        format.html { render :new }
        format.json { render json: @server.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /servers/1
  # PATCH/PUT /servers/1.json
  def update
    respond_to do |format|
      if @server.update(server_params)
        format.html { redirect_to @server, notice: 'Server was successfully updated.' }
        format.json { render :show, status: :ok, location: @server }
      else
        format.html { render :edit }
        format.json { render json: @server.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /servers/1
  # DELETE /servers/1.json
  def destroy
    @server.destroy
    respond_to do |format|
      format.html { redirect_to servers_url, notice: 'Server was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_server
      @server = Server.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def server_params
      params.require(:server).permit(:name, :ip_address)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end

  def show
  	@user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)    # Not the final implementation!
    if @user.save
      redirect_to @user
    else
      render 'new'
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/servers_helper.rb
module ServersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/_form.html.erb
<%= form_for([@list, @item]) do |f| %>
	<div class="field">
		<%= f.label :name %><br>
		<%= f.text_field :name %>
	</div>
	<div class="field">
		<%= f.label :price %><br>
		<%= f.text_field :price %>
	</div>
	<div class="field">
		<%= f.label :quantity %><br>
		<%= f.number_field :quantity %>
	</div>
	<div class="field">
		<%= f.label :quantity %><br>
		<%= f.number_field :quantity %>
	</div>
	<div class="actions">
		<%= f.submit %>
	</div>
<% end %>

app/views/items/edit.html.erb
<h1>Update</h1>

<%= render 'form' %>

<%= link_to 'Show', [@list, @item] %> |
<%= link_to 'Back', list_items_path(@list, @item) %>

app/views/items/edit_multiple.html.erb
<h1>Edit Checked Items</h1>

<%= form_tag update_multiple_list_items_path, method: :put do %>
	
	<% @items.each do |item| %>
		
		<%= fields_for "items[]", item do |f| %>
		
		<h2><%= item.name %></h2>
		
			<div class="field">
				<%= f.label :name %><br>
				<%= f.text_field :name %>
			</div>
			<div class="field">
				<%= f.label :price %><br>
				<%= f.text_field :price %>
			</div>
			<div class="field">
				<%= f.label :quantity %><br>
				<%= f.number_field :quantity %>
			</div>
			<div class="field">
				<%= f.label :purchased %><br>
				<%= f.check_box :purchased %>
			</div>

		<% end %>
	<% end %>

		<div class="actions">
			<%= submit_tag "Update" %>
		</div>
<% end %>

app/views/items/index.html.erb
<ul>
<% @items.each do |item| %>
	<li><%= item.name.titleize %> - <%= number_to_currency (item.price * item.quantity) %></li>
<% end %>
</ul>
<h2><%= @items.sum(:quantity) %> items</h2>
<h1>Total: <%= number_to_currency @items.sum(:price) %></h1>

<%= link_to "Back", list_path(@list) %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= form_for([@list, @item]) do |f| %>
	<div class="field">
		<%= f.label :name %><br>
		<%= f.text_field :name %>
	</div>
	<div class="field">
		<%= f.label :price %><br>
		<%= f.text_field :price %>
	</div>
	<div class="field">
		<%= f.label :quantity %><br>
		<%= f.number_field :quantity %>
	</div>
	<div class="field">
		<%= f.label :purchased %><br>
		<%= f.check_box :purchased %>
	</div>
	<div class="actions">
		<%= f.submit %>
	</div>
<% end %>

app/views/items/show.html.erb
<h1><%= @item.name %></h1>

<p><%= number_to_currency @item.price %></p>
<p><%= @item.location %></p>
<p><%= @item.quantity %></p>
<p><%= @item.brand %></p>

<%= link_to "Back to List", list_path(@list) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GroceryApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% flash.each do |name, msg| %>
    <%= content_tag :div, msg, :id => "notice" if msg.is_a?(String) %>
  <% end %> 
  <div class="container">
    <%= yield %>
  </div>
<%= debug(params) if Rails.env.development? %>

</body>
</html>

app/views/lists/index.html.erb
<h1>Lists</h1>

<ul>
<% @lists.each do |list| %>
	<li><%= link_to list.name, list_path(list) %> (<%= time_ago_in_words list.created_at %>)
			<%= link_to "Delete", list_path(list), method: :delete, data: { confirm: "Are you sure?" }  %>
	</li>
<% end %>
</ul>

<%= link_to "Create List", new_list_path %>

app/views/lists/new.html.erb
<h1>New List</h1>

<%= form_for @list do |f| %>
	<div class="field">
		<%= f.label :name %><br>
		<%= f.text_field :name %>
	</div>
	<div class="field">
		<%= f.label :location %><br>
		<%= f.text_field :location %>
	</div>
	<div class="actions">
		<%= f.submit %>
	</div>
<% end %>

app/views/lists/show.html.erb
<h1><%= @list.name %></h1>

<%= form_tag edit_multiple_list_items_path(@list), method: :get do %>
<table class="table">
	<tr>
		<th>&nbsp;</th>
		<th>Name</th>
		<th>Purchased?</th>
		<th>Price</th>
	</tr>
	<% @items.each do |item| %>
	<tr>
		<td><%= check_box_tag "item_ids[]", item.id %></td>
		<td><%= item.name %></td>
		<td><%= item.purchased ? "Yes" : "No" %></td>
		<td><%= number_to_currency (item.price * item.quantity) %></td>
		<td><%= link_to 'Delete', [@list, item], method: :delete, data: { confirm: "Are you sure?" }  %></td>
	</tr>
	<% end %>
</table>
<%= submit_tag "Edit Checked" %>
<% end %>


<%= link_to 'New Item', new_list_item_path(@list) %>
<%= link_to 'Back to Lists', lists_path %>
<%= link_to 'Item Details', list_items_path(@list) %>

app/views/servers/_form.html.erb
<%= form_for(@server) do |f| %>
  <% if @server.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@server.errors.count, "error") %> prohibited this server from being saved:</h2>

      <ul>
      <% @server.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :ip_address %><br>
    <%= f.text_field :ip_address %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/servers/edit.html.erb
<h1>Editing server</h1>

<%= render 'form' %>

<%= link_to 'Show', @server %> |
<%= link_to 'Back', servers_path %>

app/views/servers/index.html.erb
<%= image_tag "guitar.jpeg" %>

<h1>Listing servers</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Ip address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @servers.each do |server| %>
      <tr>
        <td><%= server.name %></td>
        <td><%= server.ip_address %></td>
        <td><%= link_to 'Show', server %></td>
        <td><%= link_to 'Edit', edit_server_path(server) %></td>
        <td><%= link_to 'Destroy', server, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Server', new_server_path %>

app/views/servers/new.html.erb
<h1>New server</h1>

<%= render 'form' %>

<%= link_to 'Back', servers_path %>

app/views/servers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @server.name %>
</p>

<p>
  <strong>Ip address:</strong>
  <%= @server.ip_address %>
</p>

<%= link_to 'Edit', edit_server_path(@server) %> |
<%= link_to 'Back', servers_path %>

app/views/users/new.html.erb
<h1>Sign up</h1>
<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<h1><%= @user.name %></h1>